class AcademicResourceModel {
  final String id;
  final String title;
  final String description;
  final String category;
  final String resourceType; // SELL, BORROW, EXCHANGE, DONATE, REQUEST
  final double price;
  final String condition;
  final String pickupLocation;
  final String sellerId;
  final String sellerName;
  final double sellerRating;
  final bool isVerifiedSeller;
  final String university;
  final List<String> imageUrls;
  final DateTime createdAt;
  final bool isAvailable;
  final String? exchangeForRequirement;
  final int? maxBorrowDays;
  final bool isRecommended;
  final bool isNearby;
  final bool isMyActiveRequest;
  final int? distanceMeters;
  final String? courseCode;

  const AcademicResourceModel({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.resourceType,
    required this.price,
    required this.condition,
    required this.pickupLocation,
    required this.sellerId,
    required this.sellerName,
    required this.sellerRating,
    required this.isVerifiedSeller,
    required this.university,
    required this.imageUrls,
    required this.createdAt,
    this.isAvailable = true,
    this.exchangeForRequirement,
    this.maxBorrowDays,
    this.isRecommended = false,
    this.isNearby = false,
    this.isMyActiveRequest = false,
    this.distanceMeters,
    this.courseCode,
  });

  factory AcademicResourceModel.fromJson(Map<String, dynamic> json) {
    return AcademicResourceModel(
      id: json['id'] as String,
      title: json['title'] as String,
      description: json['description'] as String,
      category: json['category'] as String,
      resourceType: json['resourceType'] as String,
      price: (json['price'] as num).toDouble(),
      condition: json['condition'] as String,
      pickupLocation: json['pickupLocation'] as String,
      sellerId: json['sellerId'] as String,
      sellerName: json['sellerName'] as String,
      sellerRating: (json['sellerRating'] as num).toDouble(),
      isVerifiedSeller: json['isVerifiedSeller'] as bool? ?? true,
      university: json['university'] as String,
      imageUrls: (json['imageUrls'] as List<dynamic>).cast<String>(),
      createdAt: DateTime.parse(json['createdAt'] as String),
      isAvailable: json['isAvailable'] as bool? ?? true,
      exchangeForRequirement: json['exchangeForRequirement'] as String?,
      maxBorrowDays: json['maxBorrowDays'] as int?,
      isRecommended: json['isRecommended'] as bool? ?? false,
      isNearby: json['isNearby'] as bool? ?? false,
      isMyActiveRequest: json['isMyActiveRequest'] as bool? ?? false,
      distanceMeters: json['distanceMeters'] as int?,
      courseCode: json['courseCode'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'category': category,
      'resourceType': resourceType,
      'price': price,
      'condition': condition,
      'pickupLocation': pickupLocation,
      'sellerId': sellerId,
      'sellerName': sellerName,
      'sellerRating': sellerRating,
      'isVerifiedSeller': isVerifiedSeller,
      'university': university,
      'imageUrls': imageUrls,
      'createdAt': createdAt.toIso8601String(),
      'isAvailable': isAvailable,
      'exchangeForRequirement': exchangeForRequirement,
      'maxBorrowDays': maxBorrowDays,
      'isRecommended': isRecommended,
      'isNearby': isNearby,
      'isMyActiveRequest': isMyActiveRequest,
      'distanceMeters': distanceMeters,
      'courseCode': courseCode,
    };
  }

  AcademicResourceModel copyWith({
    String? id,
    String? title,
    String? description,
    String? category,
    String? resourceType,
    double? price,
    String? condition,
    String? pickupLocation,
    String? sellerId,
    String? sellerName,
    double? sellerRating,
    bool? isVerifiedSeller,
    String? university,
    List<String>? imageUrls,
    DateTime? createdAt,
    bool? isAvailable,
    String? exchangeForRequirement,
    int? maxBorrowDays,
    bool? isRecommended,
    bool? isNearby,
    bool? isMyActiveRequest,
    int? distanceMeters,
    String? courseCode,
  }) {
    return AcademicResourceModel(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      category: category ?? this.category,
      resourceType: resourceType ?? this.resourceType,
      price: price ?? this.price,
      condition: condition ?? this.condition,
      pickupLocation: pickupLocation ?? this.pickupLocation,
      sellerId: sellerId ?? this.sellerId,
      sellerName: sellerName ?? this.sellerName,
      sellerRating: sellerRating ?? this.sellerRating,
      isVerifiedSeller: isVerifiedSeller ?? this.isVerifiedSeller,
      university: university ?? this.university,
      imageUrls: imageUrls ?? this.imageUrls,
      createdAt: createdAt ?? this.createdAt,
      isAvailable: isAvailable ?? this.isAvailable,
      exchangeForRequirement: exchangeForRequirement ?? this.exchangeForRequirement,
      maxBorrowDays: maxBorrowDays ?? this.maxBorrowDays,
      isRecommended: isRecommended ?? this.isRecommended,
      isNearby: isNearby ?? this.isNearby,
      isMyActiveRequest: isMyActiveRequest ?? this.isMyActiveRequest,
      distanceMeters: distanceMeters ?? this.distanceMeters,
      courseCode: courseCode ?? this.courseCode,
    );
  }

  static List<AcademicResourceModel> get mockResources => [
    // Recommended For You (From Reference Design)
    AcademicResourceModel(
      id: 'res_rec_01',
      title: 'Engineering Mechanics',
      description: 'Standard textbook in good condition with clear diagrams and practice problems.',
      category: 'Books',
      resourceType: 'SELL',
      price: 250.0,
      condition: 'Good',
      pickupLocation: 'Engineering Quad Bench A',
      sellerId: 'user_102',
      sellerName: 'John Doe',
      sellerRating: 4.8,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c'],
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
      isAvailable: true,
      isRecommended: true,
      courseCode: 'ME 101',
    ),
    AcademicResourceModel(
      id: 'res_rec_02',
      title: 'Scientific Calculator',
      description: 'Casio fx-991EX Classwiz scientific calculator in like new condition with cover.',
      category: 'Calculators',
      resourceType: 'SELL',
      price: 500.0,
      condition: 'Like New',
      pickupLocation: 'Main Library Student Lounge',
      sellerId: 'user_103',
      sellerName: 'Priya Sharma',
      sellerRating: 4.7,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd'],
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      isAvailable: true,
      isRecommended: true,
      courseCode: 'MATH 51',
    ),
    AcademicResourceModel(
      id: 'res_rec_03',
      title: 'Drawing Kit',
      description: 'Complete engineering drawing instruments set in portable black protective case.',
      category: 'Drawing Kits',
      resourceType: 'SELL',
      price: 300.0,
      condition: 'Good',
      pickupLocation: 'Design Center Atrium',
      sellerId: 'user_104',
      sellerName: 'Rahul Verma',
      sellerRating: 4.9,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1513542789411-b6a5d4f31634'],
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      isAvailable: true,
      isRecommended: true,
      courseCode: 'ARCH 101',
    ),
    AcademicResourceModel(
      id: 'res_rec_04',
      title: 'Arduino Uno',
      description: 'Original Arduino Uno Rev 3 development board with USB cable.',
      category: 'Electronics',
      resourceType: 'SELL',
      price: 600.0,
      condition: 'Like New',
      pickupLocation: 'Packard Electrical Building',
      sellerId: 'user_105',
      sellerName: 'Siddhant U.',
      sellerRating: 4.6,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1518770660439-4636190af475'],
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      isAvailable: true,
      isRecommended: true,
      courseCode: 'EE 108',
    ),

    // Recent Listings Near You (From Reference Design)
    AcademicResourceModel(
      id: 'res_near_01',
      title: 'Engineering Drawing Book',
      description: 'Engineering graphics workbook with drafting exercises.',
      category: 'Books',
      resourceType: 'SELL',
      price: 200.0,
      condition: 'Good',
      pickupLocation: 'Campus Central Library',
      sellerId: 'user_106',
      sellerName: 'Aarav Patel',
      sellerRating: 4.8,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c'],
      createdAt: DateTime.now().subtract(const Duration(minutes: 25)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 200,
      courseCode: 'ARCH 101',
    ),
    AcademicResourceModel(
      id: 'res_near_02',
      title: 'Digital Multimeter',
      description: 'Yellow handheld digital multimeter with testing probes for circuits.',
      category: 'Tools',
      resourceType: 'SELL',
      price: 450.0,
      condition: 'Good',
      pickupLocation: 'Science & Tech Quad',
      sellerId: 'user_107',
      sellerName: 'Neha Sen',
      sellerRating: 4.9,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758'],
      createdAt: DateTime.now().subtract(const Duration(minutes: 50)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 350,
      courseCode: 'PHYS 41',
    ),
    AcademicResourceModel(
      id: 'res_near_03',
      title: 'Lab Kit',
      description: 'Components kit with glassware, test tubes, and safety goggles.',
      category: 'Lab Components',
      resourceType: 'SELL',
      price: 750.0,
      condition: 'Like New',
      pickupLocation: 'Chemistry Wing A',
      sellerId: 'user_108',
      sellerName: 'Rohan Joshi',
      sellerRating: 4.7,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b'],
      createdAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 15)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 400,
      courseCode: 'CHEM 31A',
    ),
    AcademicResourceModel(
      id: 'res_near_04',
      title: 'Project Board',
      description: 'Breadboard and development prototyping board for robotics.',
      category: 'Project Materials',
      resourceType: 'SELL',
      price: 150.0,
      condition: 'Good',
      pickupLocation: 'Student Union Center',
      sellerId: 'user_109',
      sellerName: 'Kunal M.',
      sellerRating: 4.6,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1518770660439-4636190af475'],
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 500,
      courseCode: 'CS 106B',
    ),
    AcademicResourceModel(
      id: 'res_near_05',
      title: 'Physics Textbook',
      description: 'Concepts of Physics for foundational science courses.',
      category: 'Books',
      resourceType: 'SELL',
      price: 220.0,
      condition: 'Good',
      pickupLocation: 'South Quad Bench',
      sellerId: 'user_110',
      sellerName: 'Tanvi Shah',
      sellerRating: 4.8,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8'],
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 650,
      courseCode: 'PHYS 41',
    ),

    // Additional Demo Academic Resources
    AcademicResourceModel(
      id: 'res_demo_01',
      title: 'Python Data Structures & Algorithms',
      description: 'Comprehensive DSA handbook with practice code, Big-O sheets, and interview problems.',
      category: 'Books',
      resourceType: 'SELL',
      price: 350.0,
      condition: 'Like New',
      pickupLocation: 'Gates Computer Science Building',
      sellerId: 'user_111',
      sellerName: 'Aditya Rao',
      sellerRating: 4.9,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1526379095098-d400fd0bf935'],
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      isAvailable: true,
      isRecommended: true,
      courseCode: 'CS 106B',
    ),
    AcademicResourceModel(
      id: 'res_demo_02',
      title: 'Organic Chemistry Molecular Model Kit',
      description: 'Full 240-piece 3D molecular structure modeling set with ball-and-stick bonds.',
      category: 'Lab Components',
      resourceType: 'BORROW',
      price: 150.0,
      condition: 'Like New',
      pickupLocation: 'Chemistry Wing A',
      sellerId: 'user_112',
      sellerName: 'Meera Nair',
      sellerRating: 4.8,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1532094349884-543bc11b234d'],
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 300,
      courseCode: 'CHEM 31A',
    ),
    AcademicResourceModel(
      id: 'res_demo_03',
      title: 'Texas Instruments TI-84 Plus CE',
      description: 'Rechargeable color screen graphing calculator with charger and protective case.',
      category: 'Calculators',
      resourceType: 'SELL',
      price: 950.0,
      condition: 'Like New',
      pickupLocation: 'Main Library Student Lounge',
      sellerId: 'user_113',
      sellerName: 'Kavita Singh',
      sellerRating: 5.0,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd'],
      createdAt: DateTime.now().subtract(const Duration(hours: 7)),
      isAvailable: true,
      isRecommended: true,
      courseCode: 'MATH 51',
    ),
    AcademicResourceModel(
      id: 'res_demo_04',
      title: 'Architectural Drafting T-Square & Triangles',
      description: 'Transparent acrylic 24-inch T-square and 30/60/90 drafting triangles.',
      category: 'Drawing Kits',
      resourceType: 'DONATE',
      price: 0.0,
      condition: 'Good',
      pickupLocation: 'Design Center Atrium',
      sellerId: 'user_101', // Listed by Aniket!
      sellerName: 'Aniket',
      sellerRating: 4.9,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1513542789411-b6a5d4f31634'],
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 450,
      courseCode: 'ARCH 101',
    ),
    AcademicResourceModel(
      id: 'res_demo_05',
      title: 'Electronics Prototyping Sensor Kit',
      description: 'Ultrasonic, IR, DHT11 temp sensors, relays, and jumper wires for IoT projects.',
      category: 'Project Materials',
      resourceType: 'EXCHANGE',
      price: 0.0,
      condition: 'Like New',
      pickupLocation: 'Packard Electrical Building',
      sellerId: 'user_101', // Listed by Aniket!
      sellerName: 'Aniket',
      sellerRating: 4.9,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1518770660439-4636190af475'],
      createdAt: DateTime.now().subtract(const Duration(hours: 10)),
      isAvailable: true,
      courseCode: 'EE 108',
      exchangeForRequirement: 'Raspberry Pi Pico or ESP32 Module',
    ),
    AcademicResourceModel(
      id: 'res_demo_06',
      title: 'Temperature-Controlled Soldering Station',
      description: '60W soldering iron kit with brass sponge, stand, lead-free solder wire, and extra tips.',
      category: 'Tools',
      resourceType: 'SELL',
      price: 490.0,
      condition: 'Good',
      pickupLocation: 'Robotics Workshop B2',
      sellerId: 'user_114',
      sellerName: 'Sanjay Deshmukh',
      sellerRating: 4.7,
      isVerifiedSeller: true,
      university: 'Stanford University',
      imageUrls: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758'],
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 550,
      courseCode: 'EE 108',
    ),
  ];
}
