class AcademicResourceModel {
  final String id;
  final String title;
  final String description;
  final String category;
  final String resourceType; // SELL, BORROW, EXCHANGE, DONATE, REQUEST
  final double price;
  final String condition;
  final String pickupLocation;
  final String sellerId;
  final String sellerName;
  final double sellerRating;
  final bool isVerifiedSeller;
  final String university;
  final List<String> imageUrls;
  final DateTime createdAt;
  final bool isAvailable;
  final String? exchangeForRequirement;
  final int? maxBorrowDays;
  final bool isRecommended;
  final bool isNearby;
  final bool isMyActiveRequest;
  final int? distanceMeters;
  final String? courseCode;

  const AcademicResourceModel({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.resourceType,
    required this.price,
    required this.condition,
    required this.pickupLocation,
    required this.sellerId,
    required this.sellerName,
    required this.sellerRating,
    required this.isVerifiedSeller,
    required this.university,
    required this.imageUrls,
    required this.createdAt,
    this.isAvailable = true,
    this.exchangeForRequirement,
    this.maxBorrowDays,
    this.isRecommended = false,
    this.isNearby = false,
    this.isMyActiveRequest = false,
    this.distanceMeters,
    this.courseCode,
  });

  factory AcademicResourceModel.fromJson(Map<String, dynamic> json) {
    return AcademicResourceModel(
      id: (json['id'] ?? '').toString(),
      title: (json['title'] ?? '').toString(),
      description: (json['description'] ?? '').toString(),
      category: (json['category'] ?? 'General').toString(),
      resourceType: (json['resourceType'] ?? json['transactionType'] ?? json['type'] ?? 'SELL').toString().toUpperCase(),
      price: (json['price'] as num?)?.toDouble() ?? 0.0,
      condition: (json['condition'] ?? 'Good').toString(),
      pickupLocation: (json['pickupLocation'] ?? json['pickupLocationName'] ?? 'MIT CSN Main Gate Security Post').toString(),
      sellerId: (json['sellerId'] ?? json['ownerId'] ?? '').toString(),
      sellerName: (json['sellerName'] ?? json['ownerName'] ?? 'MIT CSN Student').toString(),
      sellerRating: (json['sellerRating'] as num?)?.toDouble() ?? 5.0,
      isVerifiedSeller: json['isVerifiedSeller'] as bool? ?? true,
      university: (json['university'] ?? json['collegeName'] ?? 'MIT CSN').toString(),
      imageUrls: (json['imageUrls'] as List<dynamic>?)?.map((e) => e.toString()).toList() ??
          (json['images'] as List<dynamic>?)?.map((e) => e.toString()).toList() ??
          const ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c'],
      createdAt: json['createdAt'] != null
          ? (DateTime.tryParse(json['createdAt'].toString()) ?? DateTime.now())
          : DateTime.now(),
      isAvailable: json['isAvailable'] as bool? ?? true,
      exchangeForRequirement: (json['exchangeForRequirement'] ?? json['exchangePreferences']) as String?,
      maxBorrowDays: json['maxBorrowDays'] as int?,
      isRecommended: json['isRecommended'] as bool? ?? false,
      isNearby: json['isNearby'] as bool? ?? false,
      isMyActiveRequest: json['isMyActiveRequest'] as bool? ?? false,
      distanceMeters: json['distanceMeters'] as int?,
      courseCode: json['courseCode'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'category': category,
      'resourceType': resourceType,
      'price': price,
      'condition': condition,
      'pickupLocation': pickupLocation,
      'sellerId': sellerId,
      'sellerName': sellerName,
      'sellerRating': sellerRating,
      'isVerifiedSeller': isVerifiedSeller,
      'university': university,
      'imageUrls': imageUrls,
      'createdAt': createdAt.toIso8601String(),
      'isAvailable': isAvailable,
      'exchangeForRequirement': exchangeForRequirement,
      'maxBorrowDays': maxBorrowDays,
      'isRecommended': isRecommended,
      'isNearby': isNearby,
      'isMyActiveRequest': isMyActiveRequest,
      'distanceMeters': distanceMeters,
      'courseCode': courseCode,
    };
  }

  AcademicResourceModel copyWith({
    String? id,
    String? title,
    String? description,
    String? category,
    String? resourceType,
    double? price,
    String? condition,
    String? pickupLocation,
    String? sellerId,
    String? sellerName,
    double? sellerRating,
    bool? isVerifiedSeller,
    String? university,
    List<String>? imageUrls,
    DateTime? createdAt,
    bool? isAvailable,
    String? exchangeForRequirement,
    int? maxBorrowDays,
    bool? isRecommended,
    bool? isNearby,
    bool? isMyActiveRequest,
    int? distanceMeters,
    String? courseCode,
  }) {
    return AcademicResourceModel(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      category: category ?? this.category,
      resourceType: resourceType ?? this.resourceType,
      price: price ?? this.price,
      condition: condition ?? this.condition,
      pickupLocation: pickupLocation ?? this.pickupLocation,
      sellerId: sellerId ?? this.sellerId,
      sellerName: sellerName ?? this.sellerName,
      sellerRating: sellerRating ?? this.sellerRating,
      isVerifiedSeller: isVerifiedSeller ?? this.isVerifiedSeller,
      university: university ?? this.university,
      imageUrls: imageUrls ?? this.imageUrls,
      createdAt: createdAt ?? this.createdAt,
      isAvailable: isAvailable ?? this.isAvailable,
      exchangeForRequirement: exchangeForRequirement ?? this.exchangeForRequirement,
      maxBorrowDays: maxBorrowDays ?? this.maxBorrowDays,
      isRecommended: isRecommended ?? this.isRecommended,
      isNearby: isNearby ?? this.isNearby,
      isMyActiveRequest: isMyActiveRequest ?? this.isMyActiveRequest,
      distanceMeters: distanceMeters ?? this.distanceMeters,
      courseCode: courseCode ?? this.courseCode,
    );
  }

  static List<AcademicResourceModel> get mockResources => [
    // Recommended For You (MIT CSN)
    AcademicResourceModel(
      id: 'res_rec_01',
      title: 'Engineering Mechanics (Statics & Dynamics 14th Ed)',
      description: 'Standard textbook in good condition with clear diagrams and practice problems for ME 101 at MIT CSN.',
      category: 'Books',
      resourceType: 'SELL',
      price: 350.0,
      condition: 'Like New',
      pickupLocation: 'MIT CSN Central Library Ground Floor',
      sellerId: 'user_101',
      sellerName: 'Aniket Sharma',
      sellerRating: 4.9,
      isVerifiedSeller: true,
      university: 'MIT CSN',
      imageUrls: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c'],
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
      isAvailable: true,
      isRecommended: true,
      courseCode: 'ME 101',
    ),
    AcademicResourceModel(
      id: 'res_rec_02',
      title: 'TI-84 Plus CE Graphing Calculator',
      description: 'Color screen, rechargeable battery included. Excellent for Linear Algebra, Calculus and Signal Processing.',
      category: 'Calculators',
      resourceType: 'SELL',
      price: 1200.0,
      condition: 'Good',
      pickupLocation: 'MIT CSN Main Gate Security Post',
      sellerId: 'user_103',
      sellerName: 'Priya Sharma',
      sellerRating: 4.8,
      isVerifiedSeller: true,
      university: 'MIT CSN',
      imageUrls: ['https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd'],
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      isAvailable: true,
      isRecommended: true,
      courseCode: 'MATH 51',
    ),
    AcademicResourceModel(
      id: 'res_rec_03',
      title: 'Drawing Kit & Instruments Set',
      description: 'Complete engineering drawing instruments set in portable black protective case.',
      category: 'Drawing Kits',
      resourceType: 'SELL',
      price: 300.0,
      condition: 'Good',
      pickupLocation: 'Computer Science & Engineering Block Atrium',
      sellerId: 'user_104',
      sellerName: 'Rahul Verma',
      sellerRating: 5.0,
      isVerifiedSeller: true,
      university: 'MIT CSN',
      imageUrls: ['https://images.unsplash.com/photo-1513542789411-b6a5d4f31634'],
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      isAvailable: true,
      isRecommended: true,
      courseCode: 'ARCH 101',
    ),
    AcademicResourceModel(
      id: 'res_rec_04',
      title: 'Arduino Uno Rev 3 & Sensor Lab Kit',
      description: 'Full microcontroller kit with breadboard, ultrasonic sensor, servo motors, and jumper wires.',
      category: 'Lab Components',
      resourceType: 'BORROW',
      price: 150.0,
      condition: 'Like New',
      pickupLocation: 'Computer Science & Engineering Block Atrium',
      sellerId: 'user_103',
      sellerName: 'Priya Sharma',
      sellerRating: 4.8,
      isVerifiedSeller: true,
      university: 'MIT CSN',
      imageUrls: ['https://images.unsplash.com/photo-1553406830-ef2513450d76'],
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      isAvailable: true,
      isRecommended: true,
      maxBorrowDays: 14,
      courseCode: 'EE 108',
    ),

    // Recent Listings Near You (MIT CSN)
    AcademicResourceModel(
      id: 'res_near_01',
      title: 'Raspberry Pi 4 Model B (4GB RAM)',
      description: 'Works perfectly in aluminum heatsink case with 32GB MicroSD. Looking to exchange for FPGA board.',
      category: 'Electronics',
      resourceType: 'EXCHANGE',
      price: 0.0,
      condition: 'Excellent',
      pickupLocation: 'MIT CSN Central Library Ground Floor',
      sellerId: 'user_101',
      sellerName: 'Aniket Sharma',
      sellerRating: 4.9,
      isVerifiedSeller: true,
      university: 'MIT CSN',
      imageUrls: ['https://images.unsplash.com/photo-1517055729441-db3a681329a2'],
      createdAt: DateTime.now().subtract(const Duration(minutes: 25)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 100,
      exchangeForRequirement: 'Basys 3 FPGA Board or STM32 Discovery kit',
    ),
    AcademicResourceModel(
      id: 'res_near_02',
      title: 'Architectural Drafting T-Square & Set Triangles',
      description: 'Graduating senior donating drafting tools. Passing on free to 1st year MIT CSN engineering student.',
      category: 'Drawing Kits',
      resourceType: 'DONATE',
      price: 0.0,
      condition: 'Good',
      pickupLocation: 'MIT CSN Main Gate Security Post',
      sellerId: 'user_101',
      sellerName: 'Aniket Sharma',
      sellerRating: 4.9,
      isVerifiedSeller: true,
      university: 'MIT CSN',
      imageUrls: ['https://images.unsplash.com/photo-1581291518857-4e27b48ff24e'],
      createdAt: DateTime.now().subtract(const Duration(minutes: 50)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 150,
      courseCode: 'ARCH 101',
    ),
    AcademicResourceModel(
      id: 'res_near_03',
      title: 'Digital Multimeter with Testing Probes',
      description: 'Yellow handheld digital multimeter with testing probes for electronics and lab circuits.',
      category: 'Tools',
      resourceType: 'SELL',
      price: 450.0,
      condition: 'Good',
      pickupLocation: 'Computer Science & Engineering Block Atrium',
      sellerId: 'user_104',
      sellerName: 'Rahul Verma',
      sellerRating: 5.0,
      isVerifiedSeller: true,
      university: 'MIT CSN',
      imageUrls: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758'],
      createdAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 15)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 200,
      courseCode: 'EE 108',
    ),
    AcademicResourceModel(
      id: 'res_near_04',
      title: 'Pearson MyLab Engineering Official Access Voucher',
      description: 'Transferable voucher code for Mechanics course portal. Valid through end of academic year.',
      category: 'Books',
      resourceType: 'SELL',
      price: 499.0,
      condition: 'New',
      pickupLocation: 'Campus Cafeteria Student Hub',
      sellerId: 'user_103',
      sellerName: 'Priya Sharma',
      sellerRating: 4.8,
      isVerifiedSeller: true,
      university: 'MIT CSN',
      imageUrls: ['https://images.unsplash.com/photo-1516321318423-f06f85e504b3'],
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      isAvailable: true,
      isNearby: true,
      distanceMeters: 250,
      courseCode: 'ME 201',
    ),
  ];
}
