// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHer4ZoxaBa2hGIuDnABQLNlwndwlwkw',
    appId: '1:183123201021:web:33d63a6b39adb7d6736794',
    messagingSenderId: '183123201021',
    projectId: 'campus-loop-430ab',
    authDomain: 'campus-loop-430ab.firebaseapp.com',
    storageBucket: 'campus-loop-430ab.firebasestorage.app',
    measurementId: 'G-ZQHHFM6T3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATNeuxOf4Vg-NHU8Mzt9QjERzw_eVu0MI',
    appId: '1:183123201021:android:e02b315b3eb954a4736794',
    messagingSenderId: '183123201021',
    projectId: 'campus-loop-430ab',
    storageBucket: 'campus-loop-430ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Z39aD7Dvp-X-Ax6ZGdeTK1l8Cs2Bxko',
    appId: '1:183123201021:ios:90fa9109092123f3736794',
    messagingSenderId: '183123201021',
    projectId: 'campus-loop-430ab',
    storageBucket: 'campus-loop-430ab.firebasestorage.app',
    iosBundleId: 'com.example.campusloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Z39aD7Dvp-X-Ax6ZGdeTK1l8Cs2Bxko',
    appId: '1:183123201021:ios:90fa9109092123f3736794',
    messagingSenderId: '183123201021',
    projectId: 'campus-loop-430ab',
    storageBucket: 'campus-loop-430ab.firebasestorage.app',
    iosBundleId: 'com.example.campusloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgHer4ZoxaBa2hGIuDnABQLNlwndwlwkw',
    appId: '1:183123201021:web:2be593cd5dbf0887736794',
    messagingSenderId: '183123201021',
    projectId: 'campus-loop-430ab',
    authDomain: 'campus-loop-430ab.firebaseapp.com',
    storageBucket: 'campus-loop-430ab.firebasestorage.app',
    measurementId: 'G-FEJV0VPZYK',
  );
}
